Refactoring of session & filter
pjok1122/travel-community pull request #10
Opened 2021-12-25 12:13 UTC by pjok1122

1. HttpSession -> SessionContext 사용
2. SessionContext 삽입 filter 등록
3. 로그인 인증 확인하는 Interceptor 등록

2021-12-30 05:58 UTC, LEEHANI requested changes

2021-12-30 05:58 UTC, LEEHANI commented on src/main/java/project/board/controller/LoginRestController.java
> +            return ResponseEntity.ok().body(session.getEmail());
21번째 줄이 동작하지 않습니다. @Authorization로 로그인 여부를 체크하고 바로 `return ResponseEntity.ok().body(session.getEmail());` 하도록 수정해야할 것 같아보여요.

위처럼 수정하게 되면 `회원`만 `아티클 상세보기가 가능`합니다. 
근데 만약, 상세보기를 비회원도 조회할 수 있다면 다음과 같이 그냥 두면 될 것 같아보입니다. 
```
@GetMapping("/ajax/login-check")
 public ResponseEntity<?> isLogin(@RequestAttribute SessionContext session) {
        return ResponseEntity.ok().body(session.getEmail());
 }
```

개인적으로 저는 비회원도 상세글을 볼 수 있도록 허용해야 할 것 같습니다.

2021-12-30 05:58 UTC, LEEHANI commented on src/main/java/project/board/interceptor/LoginCheckAnnotationInterceptor.java
> +        return true;
MemberRole을 체크하는 부분이 없는 것 같은데, 들어오는 요청이 USER인지 ADMIN인지 어떻게 구분하는 지 궁금합니다.

2021-12-31 07:29 UTC, pjok1122 commented on src/main/java/project/board/interceptor/LoginCheckAnnotationInterceptor.java
> +        return true;
현재 없는 기능이므로 TODO로 만들어두었습니다. 확장성을 위해 타입을 지정했을 뿐, 현재는 USER만 가능합니다.

2021-12-31 07:58 UTC, pjok1122 commented on src/main/java/project/board/controller/LoginRestController.java
> +            return ResponseEntity.ok().body(session.getEmail());
불필요한 API로 판단되어 session email을 조회하는 API로 임시 수정했습니다.

2022-01-01 07:07 UTC, LEEHANI approved these changes
👍

2022-01-01 07:07 UTC, merged